name: Go test

on:
  push:
    tags:
      - "v*"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.22.3
      - uses: actions/checkout@v2
      - name: go test
        run: go test -v -covermode atomic -coverprofile=covprofile .
