name: Go test

on:
  - push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v2
      - name: go test
        run: go test -v -covermode atomic -coverprofile=covprofile .
        